{{- if .Values.brainiac.configYamlContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brainiac.fullname" $ }}-config
data:
  brainiac.yaml: |
{{ .Values.brainiac.configYamlContent | toYaml | indent 4 }}

{{- end }}