# Project information
site_name: LibreChat

# Repository
repo_name: danny-avila/LibreChat
repo_url: https://github.com/danny-avila/LibreChat
#edit_uri: ''
edit_uri: blob/main/docs/

#set use_directory_urls to false to make the HTML embed use the same relative paths as in GitHub
use_directory_urls: false

theme:
  name: material
  logo: assets/LibreChat.svg
  favicon: assets/favicon_package/favicon-32x32.png

  palette:

    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    #- navigation.prune
    - navigation.indexes
    - navigation.top

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  # - pub-debugger # <- General purpose mkdocs debugger
  - mkdocs-nav-weight:
      section_renamed: true # If true, section name will use the title of its index instead of the folder name.
      index_weight: -10
      warning: true # Controls whether to send a Warning when invalid values are detected in markdown metadata
      reverse: false # If true, sort nav by weight from largest to smallest.
      headless_included: false
    # for more info: https://github.com/shu307/mkdocs-nav-weight?tab=readme-ov-file
  - pub-social:
      og:
        enabled: true
        locale: en_us
      twitter:
        enabled: true
    # for more info: https://github.com/mkusz/mkdocs-publisher
  - exclude:
      glob:
        - dev/* # <- exclude the docs/dev folder from the docs
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
    # https://github.com/apenwarr/mkdocs-exclude

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.librechat.ai
      name: Discord
    - icon: fontawesome/brands/github
      link: https://librechat.ai
      name: GitHub
    - icon: fontawesome/brands/youtube
      link: https://yt.librechat.ai
      name: YouTube
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.librechat.ai
      name: LinkedIn
    - icon: fontawesome/solid/feather
      link: https://demo.librechat.cfd
      name: Demo
    - icon: fontawesome/solid/face-grin-beam
      link: https://hf.librechat.ai
      name: Hugging Face

copyright:
  Â© 2023 <a href="https://github.com/danny-avila/LibreChat" target="_blank" rel="noopener">LibreChat</a>
