apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectordb
  labels:
    app: vectordb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vectordb
  template:
    metadata:
      labels:
        app: vectordb
    spec:
      containers:
        - name: vectordb
          image: "{{ .Values.vectordb.image.repository }}:{{ .Values.vectordb.image.tag }}"
          ports:
            - containerPort: {{ .Values.vectordb.service.port }}
          env:
            - name: POSTGRES_DB
              value: "mydatabase"
            - name: POSTGRES_USER
              value: "myuser"
            - name: POSTGRES_PASSWORD
              value: "mypassword"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: vectordb-pvc
