{{- if .Values.networkPolicies.enabled }}
{{- if .Values.meilisearch.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "librechat.fullname" . }}-meilisearch
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: meilisearch
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "librechat.fullname" . }}
      ports:
        - port: {{ .Values.meilisearch.service.port }}
          protocol: TCP
{{- end }}
---
{{- if .Values.redis.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "librechat.fullname" . }}-redis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "librechat.fullname" . }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - port: {{ .Values.redis.service.ports.redis }}
          protocol: TCP
{{- end }}
{{- end }}
