apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag.fullname" $ | lower}}-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  DB_HOST: {{ .Release.Name }}-postgresql.{{ .Release.Namespace | lower }}.svc.cluster.local
  {{- toYaml .Values.rag.configEnv | nindent 2 }} 