apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag.fullname" $ | lower}}-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1" # overrides configmap from maintainer
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  DB_HOST: librechat-pgvector-0.librechat-pgvector.librechat.svc.cluster.local
  DB_PORT: '5432'
  EMBEDDINGS_PROVIDER: "azure"
  EMBEDDINGS_MODEL: "text-embedding-ada-002-deployment"
  RAG_AZURE_OPENAI_ENDPOINT: "https://nodeenergy.openai.azure.com"
  RAG_AZURE_OPENAI_API_VERSION: "2023-05-15"
