apiVersion: v1
kind: Service
metadata:
  name: librechat-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "accessllm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3080
      targetPort: 3080
      protocol: TCP
      name: http
  selector:
    app: librechat-api
