apiVersion: v1
kind: Secret
metadata:
  name: librechat-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "accessllm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
