apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sandpack-bundler.yaml
  - static-browser-server.yaml

commonLabels:
  app.kubernetes.io/part-of: librechat
  app.kubernetes.io/managed-by: kustomize
