apiVersion: v2
name: librechat
description: A Helm chart for LibreChat
icon: https://www.librechat.ai/librechat_alt.svg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.9.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.

# renovate: image=ghcr.io/danny-avila/librechat
appVersion: "v0.8.1-rc2"

home: https://www.librechat.ai

dependencies:
  - name: mongodb
    version: "16.5.45"
    condition: mongodb.enabled
    repository: "https://charts.bitnami.com/bitnami"
  - name: meilisearch
    version: "0.11.0"
    condition: meilisearch.enabled
    repository: "https://meilisearch.github.io/meilisearch-kubernetes"
  - name: librechat-rag-api
    version: "0.5.2"
    condition: librechat-rag-api.enabled
    repository: file://../librechat-rag-api
