
name: Backend Unit Tests
on:
  push:
    branches: [feat/playwright-jest-cicd]
  pull_request:
    branches: [ feat/playwright-jest-cicd ]
jobs:
  tests_Backend:
    name: Run Backend unit tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CREDS_KEY: ${{ secrets.CREDS_KEY }}
      CREDS_IV: ${{ secrets.CREDS_IV }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install API dependencies
        run: cd api && npm ci --ignore-scripts

      # - name: Install Linux X64 Sharp
      #   run: npm install --platform=linux --arch=x64 --verbose sharp 

      - name: Run unit tests
        run: cd api && npm run test:ci