#github action to run unit tests for frontend with jest
name: Frontend Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests_frontend:
    name: Run frontend unit tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build Client
        run: cd client && npm run build:ci

      - name: Run unit tests
        run: cd client && npm run test:ci