name: N1 - Build and Push

env:
    # Azure ACR
    ACR_HOST: ${{ vars.REGISTRY_LOGIN_SERVER_PROD }}
    ACR_USER: ${{ secrets.REGISTRY_USERNAME_PROD }}
    ACR_PASS: ${{ secrets.REGISTRY_PASSWORD_PROD }}

on:
  workflow_dispatch:

jobs:
    build_and_push:
        runs-on: paychex-ai-platform-arc-nonprod
        steps:
            - uses: actions/checkout@v3

            - name: Create Config File
              run: |
                touch librechat.yaml && chmod 755 librechat.yaml |
                cat librechat.n1.yaml >> librechat.yaml |
                rm -rf .dockerignore |
                touch .dockerignore && chmod 755 .dockerignore |
                cat .paychex.dockerignore >> .dockerignore |
                cat .dockerignore

            - name: log in to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.ACR_HOST }}
                username: ${{ env.ACR_USER }}
                password: ${{ env.ACR_PASS }}

            - name: build and push docker container
              run: |
                docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:n1.${{ github.sha }}
                docker push ${{ env.ACR_HOST }}/paychex/librechat:n1.${{ github.sha }}

                docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:n1.latest
                docker push ${{ env.ACR_HOST }}/paychex/librechat:n1.latest

            - name: Trigger rag_api Workflow
              uses: BeewiseTechnologiesLTD/remote-workflow-trigger@v1
              with:
                target_repo: 'paychex/rag_api'
                workflow_id: '.github/workflows/n1-build-and-push.yml'
                github_token: ${{ secrets.CROSS_REPO_PAT }}
                ref: 'main'

            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                  inlineScript: |
                    az login --service-principal -u ${{secrets.ARC_RUNNER_SP_CLIENT_ID_NONPROD}} -p ${{secrets.ARC_RUNNER_SP_CLIENT_SECRET_NONPROD}} --tenant ${{secrets.AZURE_TENANT_ID}}
                    az account set --subscription "${{ secrets.AZURE_NONPROD_SUBSCRIPTION_ID }}"
                    az containerapp update \
                      --name conpaichateastusn1001 \
                      --resource-group rg-playai-eastus-n1-001 \
                      --yaml $GITHUB_WORKSPACE/az_container_app_definitions/n1_container_app_definition.yml
