name: N1 - Build and Push

env:
    # Azure ACR
    ACR_HOST: ${{ vars.REGISTRY_LOGIN_SERVER_PROD }}
    ACR_USER: ${{ secrets.REGISTRY_USERNAME_PROD }}
    ACR_PASS: ${{ secrets.REGISTRY_PASSWORD_PROD }}

on:
  workflow_dispatch:
      inputs:
          build_rag_api_image:
            description: 'Build RAG API Docker Image'
            required: true
            default: true
            type: boolean

jobs:
    build_and_push:
        runs-on: paychex-ai-platform-arc-nonprod
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0 # fetch all tags

            - name: Ensure tag ends with payx
              run: |
                if [[ ! "${{ inputs.tag }}" =~ payx$ ]]; then
                  echo "Tag must end with 'payx'."
                  exit 1
                fi

            - name: Checkout tag
              if: ${{ inputs.tag != '' }}
              run: |
                git fetch --tags
                git checkout tags/${{ inputs.tag }}

            - name: Get tag commit SHA
              id: tag_sha
              run: echo "TAG_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

            - name: Create Config File
              run: |
                touch librechat.yaml && chmod 755 librechat.yaml |
                cat librechat.n1.yml >> librechat.yaml |
                rm -rf .dockerignore |
                touch .dockerignore && chmod 755 .dockerignore |
                cat .paychex.dockerignore >> .dockerignore |
                cat .dockerignore

            - name: log in to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.ACR_HOST }}
                username: ${{ env.ACR_USER }}
                password: ${{ env.ACR_PASS }}

            - name: build and push docker container
              run: |
                docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:n1.${{ env.TAG_SHA }}
                docker push ${{ env.ACR_HOST }}/paychex/librechat:n1.${{ env.TAG_SHA }}

                docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:n1.latest
                docker push ${{ env.ACR_HOST }}/paychex/librechat:n1.latest

            - name: Trigger rag_api Workflow
              if: ${{inputs.build_rag_api_image}}
              uses: BeewiseTechnologiesLTD/remote-workflow-trigger@v1
              with:
                target_repo: 'paychex/rag_api'
                workflow_id: '.github/workflows/n1-build-and-push.yml'
                github_token: ${{ secrets.CROSS_REPO_PAT }}
                ref: 'main'

            - name: Update librechat image in YAML
              uses: mikefarah/yq@master
              with:
                cmd: yq -i '.properties.template.containers[] |= select(.name == "conpaichat").image = "${{ env.ACR_HOST }}/paychex/librechat:n1.${{ env.TAG_SHA }}"' az_container_app_definitions/n1_container_app_definition.yml

            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                  inlineScript: |
                    az login --service-principal -u ${{secrets.ARC_RUNNER_SP_CLIENT_ID_NONPROD}} -p ${{secrets.ARC_RUNNER_SP_CLIENT_SECRET_NONPROD}} --tenant ${{secrets.AZURE_TENANT_ID}}
                    az account set --subscription "${{ secrets.AZURE_NONPROD_SUBSCRIPTION_ID }}"
                    az containerapp update \
                      --name conpaichateastusn1001 \
                      --resource-group rg-playai-eastus-n1-001 \
                      --yaml $GITHUB_WORKSPACE/az_container_app_definitions/n1_container_app_definition.yml
