name: Auto Deploy in VPS after Push in Test Preview

on:
  push:
    branches:
      - dev-branch

jobs:
  deploy:
    name: Deploy to ChatG Server with dev branch

    permissions:
      deployments: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: 'actions/checkout@v2'
        with:
          ref: dev-branch
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          environment: preview

      - name: Debug - Print VPS_IP
        run: echo "VPS_IP=${{ secrets.VPS_IP }}"

      - name: Set up SSH Key and Deploy my ChatG on Server
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            git config --global url."https://${{ secrets.PERSONAL_GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"
            cd chatg/
            git pull origin dev-branch
            npm ci
            npm run frontend
            pm2 restart chatg-dev --update-env

      - name: Update deployment Status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
