name: prod - Build and Push

env:
    # Azure ACR
    ACR_HOST: ${{ vars.REGISTRY_LOGIN_SERVER_PROD }}
    ACR_USER: ${{ secrets.REGISTRY_USERNAME_PROD }}
    ACR_PASS: ${{ secrets.REGISTRY_PASSWORD_PROD }}

on:
  workflow_dispatch:
      inputs:
          build_rag_api_image:
            description: 'Build RAG API Docker Image'
            required: true
            default: true
            type: boolean
          branch:
            description: 'Branch to build'
            required: true
            default: ''
            type: string

jobs:
    build_and_push:
        runs-on: paychex-ai-platform-arc-prod
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0 # fetch all branches and tags
                ref: ${{ inputs.branch }}

            - name: Get commit SHA
              id: commit_sha
              run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

            - name: Create Config File
              run: |
                touch librechat.yaml && chmod 755 librechat.yaml |
                cat librechat.prod.yml >> librechat.yaml |
                rm -rf .dockerignore |
                touch .dockerignore && chmod 755 .dockerignore |
                cat .paychex.dockerignore >> .dockerignore |
                cat .dockerignore

            - name: log in to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.ACR_HOST }}
                username: ${{ env.ACR_USER }}
                password: ${{ env.ACR_PASS }}
                
            - name: build and push docker container
              run: |
                docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:prod.${{ env.COMMIT_SHA }}
                docker push ${{ env.ACR_HOST }}/paychex/librechat:prod.${{ env.COMMIT_SHA }}

                docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:prod.latest
                docker push ${{ env.ACR_HOST }}/paychex/librechat:prod.latest
                
            - name: Trigger rag_api Workflow
              if: ${{inputs.build_rag_api_image}}
              uses: BeewiseTechnologiesLTD/remote-workflow-trigger@v1
              with:
                target_repo: 'paychex/rag_api'
                workflow_id: '.github/workflows/prod-build-and-push.yml'
                github_token: ${{ secrets.CROSS_REPO_PAT }}
                ref: 'main'

            - name: Update librechat image in YAML
              uses: mikefarah/yq@master
              with:
                cmd: yq -i '.properties.template.containers[] |= select(.name == "conpaichat").image = "${{ env.ACR_HOST }}/paychex/librechat:prod.${{ env.COMMIT_SHA }}"' az_container_app_definitions/prod_container_app_definition.yml
                
            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                  inlineScript: |
                    az login --service-principal -u ${{secrets.ARC_RUNNER_SP_CLIENT_ID_PROD}} -p ${{secrets.ARC_RUNNER_SP_CLIENT_SECRET_PROD}} --tenant ${{secrets.AZURE_TENANT_ID}}
                    az account set --subscription "${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}"
                    az containerapp create \
                      --name conpaichateastusprod001 \
                      --resource-group rg-playai-eastus-prod-001 \
                      --yaml $GITHUB_WORKSPACE/az_container_app_definitions/prod_container_app_definition.yml
                
